---
output: pdf_document
---
      
<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->
# Introduction
  The world of Pokémon began in 1995 with pair of games Pokémon Red and Green. For Western audiences, the latter game would become known as Pokémon Blue. These two games introduced a unique system of turn-based that continues to define Pokémon games. Numerous other games have attempted to copy the Pokémon battling format, but none have been able to equal its widespread appeal and dedicated player base. With each successive iteration, new items, Pokémon types, and of course new creatures are added to the Pokémon lexicon. The world of Pokémon has continued to grow and evolve into one of the largest video games franchises to date. The most recent iteration of Pokémon games, Pokémon Sun and Moon, have continued Pokémon's commercial and historical trend of turning profits while adding layers to an already complex system of battling. 

  Since 2011 the program Pokémon Showdown has offered a simplified version of Pokémon games. This simplified version allows players to exclusively battle one another, replicating the most recent iteration of the Pokémon games in the process. This has allowed players to hone and test their Pokémon battling skills through the years. With well-over 20,000 daily registered users and counting, this program has become the go-to program to test and practice Pokémon battling strategies in the ultimate pursuit of becoming the very best that no one ever was.

However, before any formal analysis of Pokémon battling is discussed, the battling system must be rigorously detailed for laymen and theorists alike. 

First and foremost, Pokémon battling occurs exclusively between two players during a battle. Each of the two players has a team composed of six Pokémon. For the purposes of analysis, teams with duplicate Pokémon will not be considered, meaning that each team is composed of six distinct Pokémon. Each turn players simultaneously makes a decision for the Pokémon they have on the field. The decisions are then executed. The order of play is decided first by the priority of the moves being executed and then, if neither player decided on a priority move, by a comparative assessment of each Pokémon's speed. The executed moves are able to do a variety of effects to the opposing Pokémon, but once a player's Pokémon loses all of its health, an event referred to as fainting, the player must switch into another Pokémon. If a player has no other Pokémon to switch into, the battle ends. As would be expected, the player whose Pokémon have all fainted loses the battle, and the other player wins. Depending on the battle format, the team of six Pokémon is either dictated by the player or randomly assigned. 

Furthermore, each Pokémon has at most four possible moves to execute for any turn of a battle. Whenever a player has at least two Pokémon that have not fainted, they have the choice to switch into another Pokémon. Doing so counts as the player's action for the turn. Thus, players almost always have five different choices to make each turn. 

There are a number of parameters and variables to consider beyond those already detailed. While some of these parameters are fixed during the battle such as the Pokémon composing a player's team, some variables of interest are case-specific, i.e. dependent upon what moves a Pokémon has used previously, a Pokémon's held item, the fielded Pokémon's ability, etc. These parameters will be further detailed in the methodology section, along with further details on specific moves and Pokémon types. 

That being said, Pokémon must be formally denoted as a specific type of game in game theoretic terms. With this in mind, it bears noting that there are only two outcomes to any battle: One player wins and the other loses. Because of this, Pokémon is by definition a zero-sum game. However, it is important to note that there are distinct ways that a player may win or lose a game. Notably, the same set of decisions made by one player over multiple battles may not lead to the same outcome in each battle. That is to say, uniqueness of strategies is derived from the decisions of both players for any given battle. 

A point glossed over previously is the existence of different end games. Though the game ends when all of the Pokémon on one team have fainted, any player has the choice to forfeit the game any time before this occurs. Thus, the two ways to win or lose a battle are either by forfeiture or by having all of their Pokémon faint; the latter outcome is referred to as a "normal" game. Additionally, there is the potential for a game to result in a draw. However, draws result in a neutral payoff as neither player raises or lowers their ranking after a draw. 

Within the scope of game theoretic terms, it is vital to note that each player is able to see all past decisions made over the course of a battle, and that battles span over multiple turns. Speaking to the former point, players are able to recall not only their past decisions but also those of their opponent, including how much damage was done by a specific move during a previous turn. As this information is available at any time during the battle, Pokémon battling is a perfect recall game. Furthermore as each game is composed of a sequence of turns, Pokémon battling is also a sequential game. 

The points noted on information allude to a unique trait of Pokémon battling that further details the type of game Pokémon battling is: An incomplete information game. Though the extent of incompleteness is format specific, each player is given limited information about the opposing player's team at the beginning of the battle. After each turn, players are able learn not only the different moves each opposing Pokémon has, but also their abilities, held items, and sometimes what other Pokémon compose the opposing team. Generally speaking, there is almost always new information revealed each turn. The extent to which player strategies are revealed from information is an ongoing topic of discussion, both here and in current game theory literature. Naturally, the analysis of such a topic relies upon at least one apriori assumption, namely that player strategies are revealed by their past decisions. However, whether player strategies are rational and consistent is another matter entirely; nonetheless, it is important to note that incorporating such information into players own decision-making complicates analysis and is a central topic in analyzing Pokémon battling. 

Taken together, Pokémon battling is a special case of a sequential, zero-sum two-player game with incomplete information and perfect recall. As Pokémon battling lends itself to a discussion of imperfect information, it is all the more vital to consider the role of decision making in sequential games. A great portion of game theory literature has explored such topics, and this work will attempt to expand upon it. 

Theoretics aside, there are also notes on the computation side of analyzing Pokémon. In this regard, my initial computations and analysis focus on the distributions of turn length based on win type, i.e. the length of games played when one player forfeited or had all of their Pokémon faint. After distributional computations I categorize moves by their type, specifically whether a specific move is damaging, non-damaging, or a mix. After categorizing each move individually, I then categorize sets of four moves, again using categorizations of damaging, non-damaging, or a mix. Using this categorization I gauge the effectiveness of specific move sets based on their ability to faint Pokémon and by their likelihood to increase a players probability of winning.
  
Overall I explore how information gathered turn-by-turn feeds into the decision-making process of Pokémon battling. By incorporating tenants of behavioral economics and game theory, I hope to analyze and highlight phenomena that occur in the Pokémon battling simulator Pokémon Showdown. However, even more specifically I will continue the recent trend of 'Big Data' analysis to explore macro trends in player's decision making process. 

## Literature Review
A few points on Pokémon battling are worth noting as they relate to literature on game theory mentioned previously. First, each Pokémon battle lasts a finite number of turns. Furthermore, each player has finitely many choices to make at any given turn. Thus there exists finitely many pure strategies for players to choose from each game. Thus via application of Nash's Existence Theorem, Pokémon battling has at least one Nash equilibrium (Nash 1950). 

The question then is to determine what the Nash equilibrium, possibly equilibria, is in Pokémon battling. To address this question, it will be necessary to consider other theorems and propositions of Nash that relate to non-cooperative games. Namely, the goal of analyzing Pokémon battling is to determine solutions, strong solutions, and sub-solutions; however, it is possible that solutions as defined by Nash do not exist. This follows from Nash's note that non-cooperative games do not always have a solution; however there do exist sub-solutions (Nash 1951). Thus, a central question will be in determining whether Pokémon battling has a solution, and if so, if it is unique. Furthermore, it will be important to determine what sub-solutions exist, along with how parameterization potentially influences such solutions and sub-solutions.  

That being said, scant rigorous or academic research has actually been conducted within the scope of Pokémon-related topics. The most frequent publications focus either on Pokémon as a cultural phenomena or on strategy guides for Pokémon games. Importantly, these strategy guides have not specifically Pokémon battling strategies, though some have some focus on gameplay. However, no Pokémon strategy guides have analyzed Pokémon battling by using game theoretic terminology; though that isn't to say that there aren't academic publications focusing on Pokémon battling. 

Typically academic papers focusing on Pokémon battling have focused on the use of algorithms to simulate battling strategies and play against human players in Pokémon Showdown. One paper gives a rudimentary background on Pokémon battling and focuses explicitly on 1v1 battles (Gildardo 2013). Since this publication there has been more literature however. This literature includes greater nuance, notably by expanding the focus of its analysis to teams of six (Ho et al. 2016). Though the paper focused on what is currently a previous iteration of Pokémon Showdown, the iteration of Pokémon Showdown is fundamentally the same as that of the data used here. 

Furthermore, relevant documentation of this past iteration of Pokémon Showdown is available at its website http://pokemonshowdown.com/. Notably, the website for Pokémon Showdown provides a hub for information on Pokémon battling basics and specific battle format descriptions. Replays and ladder ranking are available publically, along with links to usage statistics and a damage calculator. 

  As noted previously, game theory vernacular has not entered into discussions on Pokémon battling strategies, at least in any formal setting. Applying such concepts to the context of Pokémon battling offers a formal foundation to discuss strategies and test hypotheses. In this regard, there are three main areas of game theory that intersect in the analysis of Pokémon battling. These three areas of interest include the interpretation of Pokémon battling as a zero sum game, the role of incomplete information, and the implications of Pokémon battling as a non-cooperative game. These three topics actively influence the decision-making process associated with Pokémon battling. 
  
  As noted, a central factor involved in the decision making process as it relates to game theory is the role of information, specifically how players incorporate information revealed each turn into their strategies. As information is revealed each turn, including the four moves an opposing Pokémon has, its ability, held item, along with what other Pokémon are on the opposing team, it is vital for players to determine if the information they just received is relevant. Furthermore, players need to decide if the information provides any insight into their opponent's strategy. Overall, this speaks to Pokémon not being a perfect information game. As such, it is not possible to apply Zermelo's theorem, though its negation provides insight as to the possible existence of a winning strategy (Schwalbe et al. 2001). 
  
An especially interesting addition to the analysis of incomplete information in Pokémon battling is the topic and implications of asymmetrical information. In this regard, the concepts of sunk costs and signaling may enter into the equation. Especially for the Random battle format, each player is given minimal information at the onset of the game. And while each turn, players both gain information, they may receive new information at different rates. The implications of this point may provide insight into specific strategies, and is a point of future analysis. 
  
This being said, concepts of game theory are not the only relevant ideas for analyzing Pokémon battling. In this vein, exploring whether a player will switch Pokémon will necessarily invoke ideas from game theory and behavioral economics. One specific concept engrained in behavioral economics that relates to Pokémon battling is the idea of "keeping doors open". In Chapter 6 of Ariel's work Predictably Irrational, results indicates that players prefer to keep options available even if doing so incurs costs and/or reduces their payoff. In the context of Pokémon battling, players may decide to preemptively switch Pokémon in the hopes of having that Pokémon later in the battle. However, whether this adversely influences the player is yet another subject of inquiry. 
  
  A an ending point of interest, taking into account opposing players' strategies as deduced from revealed information rubs against issues related level-K thinking. To elaborate further, knowing that a player is likely to repeat the same decision made the previous turn, players may be able optimize their decision by presuposing what decision their opponent is going to make. However, if the opposing player decides to incorporate that very assumption into their own decision, they may arrive at a vastly different outcome than would be expected. Furthermore this outcome may even be suboptimal for both players. That being said, the inclusion of level-k thinking is closely aligned to recent behavioral game theory literature. A central finding of this literature has emphasized the role of iterated reasoning, which essentializes player adaptation to other players' decision making (Wunder et al. 2011). Notably this will be a point to consider and incorporate into the analysis of Pokémon battling in a game theoretic framework. 
 
## References
* Ariely, D. (2009). Predictably irrational: The hidden forces that shape our decisions. New York, NY: Harper. Chapter 8: Keeping Doors Open (pp. 139-154).
* Schwalbe, U., & Walker, P. (2001). Zermelo and the Early History of Game Theory. Games and Economic Behavior, 34(1), 123-137. doi:10.1006/game.2000.0794
* Smogon University (n.d.). Retrieved October 31, 2016, from http://www.smogon.com/
* Pokémon Showdown! battle simulator (n.d.). Retrieved October 31, 2016, from http://pokemonshowdown.com/
* Pokémon Showdown Github Master Repository (2016). Zarel/Pokemon-Showdown. Retrieved October 31, 2016, from https://github.com/Zarel/Pokemon-Showdown/tree/master/data
* Wunder, M., Kaisers, M., Yaros, J., Littman, M., (May, 2011) Using Iterated Reasoning to Predict Opponent Strategies. Proc. of 10th Int. Conf. on Autonomous Agents and Multiagent Systems (AAMAS 2011), Tumer, Yolum, Sonenberg and Stone (eds.), 593-600. 
* Ho, H., Ramesh, V. (2016) Percymon: A Pokemon Showdown Artifical Intelligence. Retrieved October 31, 2016, from: http://robots.stanford.edu/cs221/2016/restricted/projects/vramesh2/final.pdf
* Sanchez-Ante, Gildardo (Dec., 2013) Sistemas Inteligentes: Reportes Finales Ago-Dic 2013. Retrieved October 31, 2016, from: https://www.researchgate.net/profile/Gildardo_Sanchez-Ante/publication/259343975_Sistemas_Inteligentes_Reportes_Finales_Ago-Dic_2013/links/0c96052b1d0b582e95000000.pdf#page=140
* Pokémon Company International (Nov. 21, 2014) Pokémon Omega Ruby & Pokémon Alpha Sapphire: The Official Hoenn Region Strategy Guide. 
* Nash, J. F., Jr. (1950, January 15). Equilibrium Points in n-Person Games. Proceedings of the National Academy of Sciences of the United States of America, 36(1), 48-49. Retrieved November 29, 2016, from http://www.sscnet.ucla.edu/polisci/faculty/chwe/austen/nash1950.pdf
* Nash, J. F., Jr. (1951, September). Non-Cooperative Games. The Annals of Mathematics, Second Series, 54(2), 286-295. Retrieved November 29, 2016, from http://lcm.csa.iisc.ernet.in/gametheory/Classics/NCG.pdf

## Methodology 
The data used is a compilation of battle logs from the Pokémon Showdown servers. Each battle log is stored as a separate .json file. The data spans across the year 2015, composed of four different months of data. The four months are March, June, September, and December. There are no lapses in data, i.e. each day of each month has numerous battle logs to account for. No dramatic overhaul was done to the Pokémon battling format at this time, though some minor adjustments were made. Furthermore only ranked games are included in the dataset. Ranked battles are battles that count towards a players global ranking in Pokémon Showdown. For each battle, players stand to gain or lose ranking points depending on whether they win or lose the battle.

Specific usage statistics are found in a subsidiary website, found at http://sweepercalc.com/stats/. The usage statistics track the frequency of use for specific Pokémon, items, abilities, and a host of other relevant variables for Pokémon battling.

A number of links redirect users to the host site of this game: Smogon University. The host site can be found at http://www.smogon.com/. This website offers a wide variety of resources, similar to those found at the Pokémon Showdown website. Most importantly the Smogon forums are a prominent site for discussion of Pokémon battling strategies. 

### Pokémon Battling Basics
The Pokémon battle starts with Pokémon being sent out. For the purposes of the data used, one Pokémon is sent out for each opponent, totalling two Pokémon being out at any given time. Following this, each Pokémon has 4 moves to choose from, along with the option to switch to a different Pokémon (when applicable). After both players make a decision, the moves are weighted for priority and speed to determine the order of play. If both players decide not to switch one Pokémon will attack the other, after which the next Pokémon will do the same if it has not fainted. After each move has been executed the turn ends and the process is repeated. When one of the Pokémon faints, the player whose Pokémon fainted will be prompted to select another Pokémon from the bench. The first player to lose all of their Pokémon loses the battle. 

#### Battle Formats 
The data used for this study include two different Pokémon battling formats. The two formats are known as Over Used and Random Battles, abbreviated as OU and Randbats respectively. Both formats have teams of six Pokémon and only allow one Pokémon to be out at any given time. While both battle formats are subsets of what are known as single battles, each has their own unique spin on the Pokémon battling format. 

Random Battles are the most frequently played format. Neither player gets to decide on their initial Pokémon nor do they have any input on the composition of the team. The format uses an algorithm to determine team compositions. However it is important to note that there are restrictions to the Randbats format that center around team composition and move composition for specific Pokémon. 

The Over Used battle format includes team composition. By including team composition, players are able to decide what Pokémon to include on their team, the moves of each Pokémon, and other factors such as held items and abilities. Further restrictions to the OU format include banning specific Pokémon. The restricted Pokémon are included in the "Uber" tier along with the Pokémon Mega-Rayquaza. Additionally certain "hidden" abilities are locked for Pokémon. 

### Pokémon Attributes 
Generally, there are a number of factors that are specific to each Pokémon. Some of these factors are considered static, meaning that they do not change over the course of the battle. These types of factors are noted as "Fixed" Attributes. However there are some factors that are generally regarded as Fixed Attributes but are affected by certain moves, at least when the Pokémon is sent out. These types of factors are a distinct subcategory of "Variable Attributes", and will be outlined further. Additionally there are attributes that are inherently influenced throughout the course of the battle. These are noted as "Variable Attributes". The terminology is largely taken from the Ho et al. paper for ease of translation.

####  Pokémon Types 
Currently there are 18 different Pokémon types. However, a Pokémon can be at most two different types. This means that there are actually 

The type(s) of each Pokémon influence not only the potential weaknesses of each Pokémon, but also influence the amount of damage certain type-specific moves are able to do. Each Pokémon has at least one and at most two types. If a Pokémon uses a damaging move whose type corresponds to type of the Pokémon that used it, that Pokémon gets a same type attack bonus, abbreviated as a "stab" bonus. This causes the move to do 50% more damage, potentially 100% if the Pokémon also has the ability Adaptability. 

#### Pokémon Fixed Attributes
Fixed attributes include the type(s) of the Pokémon, the four moves the Pokémon has learned, the one item the Pokémon holds, the Pokémon's one selected ability, the level of the Pokémon, and the Pokémon's baseline stats. The latter factor is divided into six categories. These categories include (baseline) Health, Attack, Special Attack, Defense, Special Defense, and Speed. There is further nuance with the inclusion of Pokémon natures and Individual Values, or IVs. These factors influence the base stats of each Pokémon. However due to the sheer number of trivial combinations of IV spreads and nature choices, these two factors will not be a pivotal aspect of framework used. 

#### Pokémon Variable Attributes
Variable Attributes include the current health of the Pokémon, the status of the Pokémon, the volatile status of the Pokémon, boost data of the Pokémon, and whether the Pokémon in question is currently active. 

## End thesis Chapter 1 

## Additional resources

- _Markdown_ Cheatsheet - <https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet>

- _R Markdown_ Reference Guide - <https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf>

- Introduction to `dplyr` - <https://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html>

- `ggplot2` Documentation - <http://docs.ggplot2.org/current/>
